# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

volumes:
  orderer.drugcounterfeit.com:
  peer0.consumer.drugcounterfeit.com:
  peer1.consumer.drugcounterfeit.com:
  peer0.distributor.drugcounterfeit.com:
  peer1.distributor.drugcounterfeit.com:
  peer0.manufacturer.drugcounterfeit.com:
  peer1.manufacturer.drugcounterfeit.com:
  peer0.retailer.drugcounterfeit.com:
  peer1.retailer.drugcounterfeit.com:
  peer0.transporter.drugcounterfeit.com:
  peer1.transporter.drugcounterfeit.com:

networks:
  pharmanet:
    name: network_pharmanet

services:

  orderer.drugcounterfeit.com:
    container_name: orderer.drugcounterfeit.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.drugcounterfeit.com:9443
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../organizations/ordererOrganizations/drugcounterfeit.com/orderers/orderer.drugcounterfeit.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/drugcounterfeit.com/orderers/orderer.drugcounterfeit.com/tls/:/var/hyperledger/orderer/tls
      - orderer.drugcounterfeit.com:/var/hyperledger/production/orderer
    ports:
      - "7050:7050"
      - "7053:7053"
      - "9443:9443"
    networks:
      - pharmanet

  peer0.consumer.drugcounterfeit.com:
    container_name: peer0.consumer.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.consumer.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer0.consumer.drugcounterfeit.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.consumer.drugcounterfeit.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.consumer.drugcounterfeit.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consumer.drugcounterfeit.com:7051
      - CORE_PEER_LOCALMSPID=consumerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.consumer.drugcounterfeit.com:9444
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/consumer.drugcounterfeit.com/peers/peer0.consumer.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer0.consumer.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "7051:7051"
      - "9444:9444"
    networks:
      - pharmanet

  peer1.consumer.drugcounterfeit.com:
    container_name: peer1.consumer.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.consumer.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer1.consumer.drugcounterfeit.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.consumer.drugcounterfeit.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.consumer.drugcounterfeit.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.consumer.drugcounterfeit.com:8051
      - CORE_PEER_LOCALMSPID=consumerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.consumer.drugcounterfeit.com:9445
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/consumer.drugcounterfeit.com/peers/peer1.consumer.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer1.consumer.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "8051:8051"
      - "9445:9445"
    networks:
      - pharmanet

  peer0.distributor.drugcounterfeit.com:
    container_name: peer0.distributor.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.distributor.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer0.distributor.drugcounterfeit.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.distributor.drugcounterfeit.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.drugcounterfeit.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.drugcounterfeit.com:9051
      - CORE_PEER_LOCALMSPID=distributorMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.distributor.drugcounterfeit.com:9446
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/distributor.drugcounterfeit.com/peers/peer0.distributor.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer0.distributor.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "9051:9051"
      - "9446:9446"
    networks:
      - pharmanet

  peer1.distributor.drugcounterfeit.com:
    container_name: peer1.distributor.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.distributor.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer1.distributor.drugcounterfeit.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.distributor.drugcounterfeit.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.distributor.drugcounterfeit.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.distributor.drugcounterfeit.com:10051
      - CORE_PEER_LOCALMSPID=distributorMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.distributor.drugcounterfeit.com:9447
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/distributor.drugcounterfeit.com/peers/peer1.distributor.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer1.distributor.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "10051:10051"
      - "9447:9447"
    networks:
      - pharmanet

  peer0.manufacturer.drugcounterfeit.com:
    container_name: peer0.manufacturer.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.manufacturer.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer0.manufacturer.drugcounterfeit.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.manufacturer.drugcounterfeit.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manufacturer.drugcounterfeit.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manufacturer.drugcounterfeit.com:11051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.manufacturer.drugcounterfeit.com:9448
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/manufacturer.drugcounterfeit.com/peers/peer0.manufacturer.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer0.manufacturer.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "11051:11051"
      - "9448:9448"
    networks:
      - pharmanet

  peer1.manufacturer.drugcounterfeit.com:
    container_name: peer1.manufacturer.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.manufacturer.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer1.manufacturer.drugcounterfeit.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.manufacturer.drugcounterfeit.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.manufacturer.drugcounterfeit.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.manufacturer.drugcounterfeit.com:12051
      - CORE_PEER_LOCALMSPID=manufacturerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.manufacturer.drugcounterfeit.com:9449
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/manufacturer.drugcounterfeit.com/peers/peer1.manufacturer.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer1.manufacturer.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "12051:12051"
      - "9449:9449"
    networks:
      - pharmanet

  peer0.retailer.drugcounterfeit.com:
    container_name: peer0.retailer.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.retailer.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer0.retailer.drugcounterfeit.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.retailer.drugcounterfeit.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailer.drugcounterfeit.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailer.drugcounterfeit.com:13051
      - CORE_PEER_LOCALMSPID=retailerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.retailer.drugcounterfeit.com:9450
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/retailer.drugcounterfeit.com/peers/peer0.retailer.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer0.retailer.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "13051:13051"
      - "9450:9450"
    networks:
      - pharmanet

  peer1.retailer.drugcounterfeit.com:
    container_name: peer1.retailer.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.retailer.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer1.retailer.drugcounterfeit.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.retailer.drugcounterfeit.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.retailer.drugcounterfeit.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.retailer.drugcounterfeit.com:14051
      - CORE_PEER_LOCALMSPID=retailerMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.retailer.drugcounterfeit.com:9451
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/retailer.drugcounterfeit.com/peers/peer1.retailer.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer1.retailer.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "14051:14051"
      - "9451:9451"
    networks:
      - pharmanet

  peer0.transporter.drugcounterfeit.com:
    container_name: peer0.transporter.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.transporter.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer0.transporter.drugcounterfeit.com:15051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_CHAINCODEADDRESS=peer0.transporter.drugcounterfeit.com:15052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:15052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.transporter.drugcounterfeit.com:15051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.transporter.drugcounterfeit.com:15051
      - CORE_PEER_LOCALMSPID=transporterMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.transporter.drugcounterfeit.com:9452
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/transporter.drugcounterfeit.com/peers/peer0.transporter.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer0.transporter.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "15051:15051"
      - "9452:9452"
    networks:
      - pharmanet

  peer1.transporter.drugcounterfeit.com:
    container_name: peer1.transporter.drugcounterfeit.com
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.transporter.drugcounterfeit.com
      - CORE_PEER_ADDRESS=peer1.transporter.drugcounterfeit.com:16051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_CHAINCODEADDRESS=peer1.transporter.drugcounterfeit.com:16052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:16052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.transporter.drugcounterfeit.com:16051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.transporter.drugcounterfeit.com:16051
      - CORE_PEER_LOCALMSPID=transporterMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.transporter.drugcounterfeit.com:9453
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    volumes:
      - ../organizations/peerOrganizations/transporter.drugcounterfeit.com/peers/peer1.transporter.drugcounterfeit.com:/etc/hyperledger/fabric
      - peer1.transporter.drugcounterfeit.com:/var/hyperledger/production
    working_dir: /root
    command: peer node start
    ports:
      - "16051:16051"
      - "9453:9453"
    networks:
      - pharmanet

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.consumer.drugcounterfeit.com
      - peer1.consumer.drugcounterfeit.com
      - peer0.distributor.drugcounterfeit.com
      - peer1.distributor.drugcounterfeit.com
      - peer0.manufacturer.drugcounterfeit.com
      - peer1.manufacturer.drugcounterfeit.com
      - peer0.retailer.drugcounterfeit.com
      - peer1.retailer.drugcounterfeit.com
      - peer0.transporter.drugcounterfeit.com
      - peer1.transporter.drugcounterfeit.com
    networks:
      - pharmanet